### ISSUE TITLE
Make file for LPC

### ISSUE THREAD

**Issue by deladriere** [ptwz/lidar_altimeter#1]
I am very surprised/ pleased by the quality of the LPC data used in this project. They sound much better than mine (also processed by your python_wizard) (I also noticed that 'ready', 'fail' and 'retard' sounds different)
Can you share the script to generate the sound wave as you did for make_sample.sh? Which voice are you using?  (Tom ?)
I also use say on Mac and prepare the sound with Sox.

I have  a Python script to process the text file line by line and generate an LPC file that my Arduino can read directly from a sd card
My flow goes like this  for each line

```
       # generate temporary audio wave with  the Mac's voice	
	system('say  -v"tom" -o audio/' +  label +'a.wave -r 140 '+ '[[slnc 10]]'+line)
	
	# convert wave to 8kHz 16 bit wav
	system('sox audio/'+ label+'a.wave  -r 8k -b16  audio/'+label+'.wav ') 
	
	#play audio
	system('afplay audio/'+ label+'.wav')
	
 	#print label to file so the Arduino can file the line in the file
	system('printf '+label+': >> '+ out)
	
	#process wave with python_wizard
	system('python python_wizard.py -u 0.93 -w 2 -S -p -a -0.9375 -m 0.9 -F 25 -f hex  audio/'+ label+'.wav >> '+ out) 
	
	#delete temporary wave
	system('rm audio/'+label+'a.wave')
```

Maybe the quality produced on my side is related on  how I use python_wizard but I want to make sure that I generate the wave file correctly before processing them with  python_wizard

**Comment by ptwz** [comment]
The samples where made using BlueWizard, for using python_wizard the script has been adapted in #1129db5 to sound quite good, too. I use the voice "Alex" of MacOS.
My arguments where -w 2 -S -p -a -1 -m 0.7 -u .5 -F 25
